footprint: [[-0.6, -0.45], [-0.6, 0.45], [0.6, 0.45], [0.6, -0.45]]
footprint_padding: 0.2
robot_base_frame: base_link
update_frequency: 10
publish_frequency: 3
transform_tolerance: 1.0
publish_voxel_map: false
use_sim_time: false

plugins:
    # - {name: static_layer,       type: "costmap_2d::StaticLayer"}
    - {name: obstacles,        type: "costmap_2d::ObstacleLayer"} #  VoxelLayer
    - {name: inflation,        type: "costmap_2d::InflationLayer"}
 
obstacles:
  track_unknown_space: false
  footprint_clearing_enabled: true
  combination_method: 1
  observation_sources: point_cloud_sensor

  # 3dmap: 
  #   data_type: PointCloud2
  #   sensor_frame: "map_transformer"
  #   topic: /cloud_pcd 

  #   observation_persistance: 0.0
  #   expected_update_rate: 0.0
  #   max_obstacle_height: 1.5
  #   min_obstacle_height: 0.3
  #   obstacle_range: 100
  #   raytrace_range: 3.0
  #   inf_is_valid: false
  #   marking: true
  #   clearing: true
      
  point_cloud_sensor: 
    data_type: PointCloud2
    sensor_frame: "velodyne"
    topic: /velodyne_points 

    observation_persistance: 0.0
    expected_update_rate: 0.0
    max_obstacle_height: 10.0
    min_obstacle_height: 0.0
    obstacle_range: 10
    raytrace_range: 3.0
    inf_is_valid: false
    marking: true
    clearing: true

inflation: 
  inflation_radius: 0.1
  cost_scaling_factor: 1.5

# static_layer:
#   map_topic: "/map"
#   first_map_only: true
