local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 0.0
  publish_frequency: 2.0
  transform_tolerance: 0.2
  static_map: false
  rolling_window: true
  width: 1.5
  height: 1.5
  origin_x: 0.0
  origin_y: 0.0
  resolution: 0.2
