base_global_planner : global_planner/GlobalPlanner
use_sim_time: false

GlobalPlanner:
  use_sim_time: false
  cost_factor: 1.0
  lethal_cost: 245
  neutral_cost: 66
  orientation_mode: 2
  publish_potential: true
  use_dijkstra: false

# base_global_planner : base_navigation::AStarPlannerGPP


